### ISSUE TITLE
App counting the call even though it doesn't go through

### ISSUE THREAD

**Issue by ChandanKumarRSI** [ChandanKumarRSI/OptarosSAPUI5POC#13]
When we make a call through the application, the call counter is increased even when the call doesn't go through.
As per the requirement (on Android), the call counter should be increased only when the call goes through successfully. And the call list should also be updated only when the call is successful.
When the call doesn't go through, the list shouldn't be updated and counter shouldn't be updated.

**Comment by effo-shesh** [comment]
fixed in the latest build

**Comment by effo-shesh** [comment]
fixed in the latest build

**Comment by effo-shesh** [comment]
fixed in the latest build
