### ISSUE TITLE
Call details not being correctly

### ISSUE THREAD

**Issue by ChandanKumarRSI** [ChandanKumarRSI/OptarosSAPUI5POC#17]
Call details do not show correctly in case multiple calls have been made to a number. 
Steps -
1. Make a call to a number. Its details show up in the list below.
2. Now make another call to the same number. Its details will show in the list.
3. Now click the details of the second call made. 
It incorrectly shows the details of the first call.

**Comment by effo-shesh** [comment]
this issue is closed in the latest build v4
