### ISSUE TITLE
Hard coded service URL in mainview controller

### ISSUE THREAD

**Issue by ChandanKumarRSI** [ChandanKumarRSI/OptarosSAPUI5POC#5]
Hard coded path of the service URL /V2/Northwind/Northwind.svc/ has been used in the mainview controller.
Can we use by creating the datasource and model in the manifest file (without pre-loading it) and then use it in our code to fetch data at runtime.
Alternatively, we can define the service URL in some config file and then use in the code.

**Comment by effo-shesh** [comment]
this not the hardcoded url, i am using the standard way to calling odata service and i have already set the destination path in neo-app.json file.
