### ISSUE TITLE
Busy indicator shown even if log-in fails

### ISSUE THREAD

**Issue by ChandanKumarRSI** [ChandanKumarRSI/OptarosSAPUI5POC#7]
In case the log-in fails, app shows the "User id or Password is wrong." information but after that the busy indicator is shown. This is incorrect behaviour.
The correct behaviour after incorrect login should be -
1. App shows the message "User id or Password is wrong."
2. The password field should become blank.
3. There should be no busy indicator after that as the credentials are being checked locally.

**Comment by ChandanKumarRSI** [comment]
I think we should remove the method call **show3000();** in method **onPressLoginBtn()**.
We should show the busy indicator only when the login is successful and the app is transitioning to the next page (mainview).

**Comment by effo-shesh** [comment]
fixed in the latest build v4
